version: '3.9'
services:
  backend:
    image: cory-home_backend
    ports:
      - "8000:8000"
    volumes:
      - ./config.env:/app/config.env
    depends_on:
      - db
  db:
    image: mysql:8.0.28
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: cory
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
